#!/usr/bin/env zsh
#
# Wrappers for my docker commands
#

export DOCKER_REPO_PREFIX=ryanjohnston
export REMOTE_ONE=sayer.ryanj.org:2376
export REMOTE_TWO=maeve.ryanj.org:2376
export DOCKER_UID=501
export DOCKER_GID=1000

#
# CONTAINERS
#

telnet() {
  docker run -it --rm \
    --name telnet \
    -v $(pwd):/workdir \
    -w /workdir \
    alpine:latest \
    /usr/bin/telnet "$@"
}

jenkins() {
  docker -H ${REMOTE_ONE} \
    --tlsverify \
    run -d --restart always \
    --name jenkins \
    -p 8080:8080 \
    -p 50000:50000 \
    --mount source=jenkins,target=/var/jenkins_home \
    ryanjohnston/jenkins
}

mysql-server () {
  docker -H ${REMOTE_ONE} \
    --tlsverify \
    run -d \
    -p 3306:3306 \
    --name mysql-server \
    --mount source=mysql,target=/var/lib/mysql \
    -e MYSQL_ROOT_PASSWORD=dietcoke99 \
    -e MYSQL_ROOT_HOST=172.17.0.1 \
    mysql/mysql-server:5.6
}

portainer () {
  docker run -d \
    -p 9000:9000 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --mount source=portainer,target=/data \
    portainer/portainer
}

base() {
  docker run -it --rm --name base -v $(pwd):/workdir -w /workdir \
  -u ${DOCKER_UID}:${DOCKER_GID} ${DOCKER_REPO_PREFIX}/base "$@"
}

certstrap() {
  docker run -it --rm --name certstrap -v $(pwd):/workdir -w /workdir \
  -u ${DOCKER_UID}:${DOCKER_GID} ${DOCKER_REPO_PREFIX}/certstrap "$@"
}

alpine() {
  docker run -it --rm --name alpine -v $(pwd):/workdir -w /workdir alpine:latest "$@"
}

node() {
  docker run -it --rm --name node -v $(pwd):/workdir -w /workdir \
  -u ${DOCKER_UID}:${DOCKER_GID} ${DOCKER_REPO_PREFIX}/node node "$@"
}

curl() {
  docker run -it --rm --name node -v $(pwd):/workdir -w /workdir \
  -u ${DOCKER_UID}:${DOCKER_GID} ${DOCKER_REPO_PREFIX}/curl "$@"
}

npm() {
  docker run -it --rm --name node -v $(pwd):/workdir -w /workdir \
  -u ${DOCKER_UID}:${DOCKER_GID} ${DOCKER_REPO_PREFIX}/node npm "$@"
}

conduct() {
  docker run -it \
    --rm \
    --name conduct \
    -v $(pwd):/workdir \
    -w /workdir \
    ${DOCKER_REPO_PREFIX}/conduct "$@"

}

hpm() {
  docker run -it --rm --name hpm -v $(echo ~):/root -w /root ${DOCKER_REPO_PREFIX}/hpm "$@"
}

composer() {
  docker run -it --rm --name composer -v $(pwd):/workdir -v ~/.ssh:/root/.ssh -w /workdir composer/composer "$@"
}

