#!/usr/bin/env zsh

jenkins() {
  docker -H sayer.ryanj.org:2376 \
    --tlsverify \
    run -d \
    --restart always \
    --name myjenkins \
    -p 8080:8080 \
    -p 50000:50000 \
    --mount source=jenkins,target=/var/jenkins_home \
    getintodevops/jenkins-withdocker
}

certstrap() {
  docker run -it --rm \
    --name certstrap \
    -v $(pwd):/workdir \
    -w /workdir \
    ryanjohnston/certstrap "$@"
}

alpine() {
  docker run -it --rm \
    --name alpine \
    -v $(pwd):/workdir \
    -w /workdir \
    alpine:latest "$@"
}

node() {
  docker run -it --rm \
    --name node \
    -v $(pwd):/workdir \
    -w /workdir \
    node:latest "$@"
}

curl() {
  docker run -it --rm \
    --name node \
    -v $(pwd):/workdir \
    -w /workdir \
    ryanjohnston/curl "$@"
}

npm() {
  docker run -it --rm \
    --name node \
    -v $(pwd):/workdir \
    -w /workdir \
    ryanjohnston/node npm "$@"
}

conduct() {
  docker run -it --rm \
    --name conduct \
    -v "$PWD":/workdir \
    -w /workdir \
    ryanjohnston/conduct "$@"
}

hpm() {
  docker run -it --rm \
    --name hpm \
    -v "$HOME":/root \
    -w /root \
    ryanjohnston/hpm "$@"
}

composer() {
  docker run -t --rm \
    -v $(pwd):/app \
    -v ~/.ssh:/root/.ssh \
    -w /app \
    composer/composer $@
}

